# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJo4gDnETVk8z7n230atlxXDJts40sQA
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

st.set_page_config(page_title="Phone Data Analysis", layout="wide")

st.title("Phone Data Analysis from CSV")

CSV_FILE = "phones_static_pagination.csv"

def clean_data(df):
    # Clean price column: remove $ and convert to float
    df['price'] = df['price'].str.replace('$', '', regex=False).astype(float)

    # Extract numeric reviews count
    df['reviews_count'] = df['reviews'].str.extract(r'(\d+)').fillna(0).astype(int)

    return df

def show_analysis(df):
    st.subheader("Summary Statistics")
    st.write(df.describe())

    st.subheader("Price Distribution")
    fig, ax = plt.subplots()
    sns.histplot(df['price'], bins=20, kde=True, ax=ax)
    st.pyplot(fig)

    st.subheader("Rating Distribution")
    fig2, ax2 = plt.subplots()
    sns.countplot(x='rating', data=df, ax=ax2)
    st.pyplot(fig2)

    st.subheader("Price vs Rating Scatter Plot")
    fig3, ax3 = plt.subplots()
    sns.scatterplot(x='price', y='rating', size='reviews_count', data=df, ax=ax3, sizes=(20, 200), alpha=0.7)
    ax3.set_xlabel("Price ($)")
    ax3.set_ylabel("Rating (stars)")
    st.pyplot(fig3)

if os.path.exists(CSV_FILE):
    df = pd.read_csv(CSV_FILE)
    df = clean_data(df)
    st.dataframe(df)

    show_analysis(df)

    csv = df.to_csv(index=False)
    st.download_button("Download cleaned CSV", data=csv, file_name="phones_cleaned.csv", mime="text/csv")
else:
    st.error(f"CSV file '{CSV_FILE}' not found in the current directory.")